"""
Knowledge-graph template induced from 1 sample document(s): sample_yaml.

Key entities:
- Company (root): Represents an organization that develops solutions and has departments and projects.
- Person: An individual associated with the company, potentially as a manager or employee.
- Department: A division within a company, responsible for specific functions.
- Project: A specific initiative or undertaking within the company.

Key relationships:
- Department --MANAGED_BY--> Person
- Department --HAS_EMPLOYEE--> Person (by reference)
- Project --OWNED_BY--> Person (by reference)
- Project --HAS_MEMBER--> Person (by reference)
- Company --HAS_DEPARTMENT--> Department
- Company --HAS_PROJECT--> Project

Generated by docling-graph template generation from sample_yaml.
"""

from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field


# -----------------------------------------------------------------------------
# Docling Graph edge helper
# -----------------------------------------------------------------------------
def edge(
    label: str,
    default: Any = None,
    *,
    reference: bool = False,
    closed_catalog: bool = False,
    **kwargs: Any,
) -> Any:
    """
    Declare a field as a graph edge for Docling-Graph via json_schema_extra.

    ``reference=True`` marks an identity-ONLY link (graph_reference): the field
    carries id-only references to entities described in full elsewhere in the
    schema. In dense extraction these references are filled by the PARENT's own
    fill call (never discovered separately), which preserves per-parent
    membership lists and avoids phantom parents.

    ``closed_catalog=True`` (reference_closed_catalog) declares that the targets
    form a CLOSED catalog defined elsewhere in the document: a target that only
    exists through this field (never instantiated or referenced otherwise) is a
    hallucinated member — the converter then drops the edge (and the orphaned
    target), unless that would wipe more than half of the target class.
    """
    json_schema_extra = dict(kwargs.pop("json_schema_extra", {}) or {})
    json_schema_extra["edge_label"] = label
    if reference:
        json_schema_extra["graph_reference"] = True
    if closed_catalog:
        json_schema_extra["reference_closed_catalog"] = True

    if "default_factory" in kwargs:
        default_factory = kwargs.pop("default_factory")
        return Field(default_factory=default_factory, json_schema_extra=json_schema_extra, **kwargs)

    return Field(default, json_schema_extra=json_schema_extra, **kwargs)


# -----------------------------------------------------------------------------
# Entities
# -----------------------------------------------------------------------------
class Person(BaseModel):
    """An individual associated with the company, potentially as a manager or employee."""

    model_config = ConfigDict(graph_id_fields=["person_id"])

    person_id: str = Field(
        ...,
        description="A unique identifier provided for each person.",
        examples=[],  # TODO(docling-graph): add 2-5 verbatim examples
    )

    name: Optional[str] = Field(
        None,
        description="LOOK FOR the 'name' field under 'manager' or 'employees' items.",
        examples=["Alice Johnson", "Bob Smith"],
    )

    role: Optional[str] = Field(
        None,
        description="LOOK FOR the 'role' field under 'manager' or 'employees' items.",
        examples=["Engineering Manager", "Backend Engineer"],
    )

    skills: List[str] = Field(
        default_factory=list,
        description="LOOK FOR the 'skills' list under 'employees' items.",
        examples=["Python", "Neo4j", "FastAPI"],
    )

    def __str__(self) -> str:
        parts = [self.person_id, self.name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class Department(BaseModel):
    """A division within a company, responsible for specific functions."""

    model_config = ConfigDict(graph_id_fields=["department_id"])

    department_id: str = Field(
        ...,
        description="A unique identifier provided for each department.",
        examples=["dept_001"],
    )

    name: Optional[str] = Field(
        None,
        description="LOOK FOR the 'name' field under each 'departments' item.",
        examples=["Engineering"],
    )

    managed_by: Optional[Person] = edge(
        label="MANAGED_BY",
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_employee: List[Person] = edge(
        label="HAS_EMPLOYEE",
        default_factory=list,
        reference=True,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    def __str__(self) -> str:
        parts = [self.department_id, self.name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


class Project(BaseModel):
    """A specific initiative or undertaking within the company."""

    model_config = ConfigDict(graph_id_fields=["project_id"])

    project_id: str = Field(
        ...,
        description="A unique identifier provided for each project.",
        examples=[],  # TODO(docling-graph): add 2-5 verbatim examples
    )

    name: Optional[str] = Field(
        None,
        description="LOOK FOR the 'name' field under each 'projects' item.",
        examples=["Knowledge Graph Platform"],
    )

    description: Optional[str] = Field(
        None,
        description="LOOK FOR the 'description' field under each 'projects' item.",
        examples=["Platform that converts enterprise documents into structured knowledge graphs."],
    )

    technologies: List[str] = Field(
        default_factory=list,
        description="LOOK FOR the 'technologies' list under each 'projects' item.",
        examples=["Docling", "Neo4j", "Python"],
    )

    owned_by: Optional[Person] = edge(
        label="OWNED_BY",
        reference=True,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_member: List[Person] = edge(
        label="HAS_MEMBER",
        default_factory=list,
        reference=True,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    def __str__(self) -> str:
        parts = [self.project_id, self.name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Root document
# -----------------------------------------------------------------------------
class Company(BaseModel):
    """Represents an organization that develops solutions and has departments and projects."""

    model_config = ConfigDict(graph_id_fields=["company_id"])

    company_id: str = Field(
        ...,
        description="A unique identifier provided for the company.",
        examples=[],  # TODO(docling-graph): add 2-5 verbatim examples
    )

    name: Optional[str] = Field(
        None,
        description="LOOK FOR the 'name' field under 'company:'.",
        examples=["Acme AI"],
    )

    description: Optional[str] = Field(
        None,
        description="LOOK FOR the 'description' field under 'company:'.",
        examples=[
            "Acme AI develops document intelligence and knowledge graph solutions for enterprise customers.",
        ],
    )

    has_department: List[Department] = edge(
        label="HAS_DEPARTMENT",
        default_factory=list,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    has_project: List[Project] = edge(
        label="HAS_PROJECT",
        default_factory=list,
        description="",  # TODO(docling-graph): add a 1-3 sentence LOOK-FOR description
    )

    def __str__(self) -> str:
        parts = [self.company_id, self.name]
        return " ".join(str(p) for p in parts if p) or "Unknown"


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
# This template passed generation gates V1-V6 (parse, import allowlist,
# load, structured-output schema, dense catalog walk, graph-shape smoke
# test). Comments never reach extraction prompts — only class docstrings
# and field descriptions do. After hand edits, re-verify with:
#
#     docling-graph template lint <module.path.Company>
